language: node_js
matrix:
  include:
    - node_js: "6.9.1"
    - node_js: "7"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
     - chrome-linux
     - lighthouse-extension/node_modules
     - lighthouse-viewer/node_modules
install:
  - npm install
  - npm run install-all
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./lighthouse-core/scripts/download-chrome.sh
  - npm run build-all
script:
  - npm run lint
  - npm run unit
  - npm run closure
  - npm run smoke
  - npm run smokehouse
after_success:
  - npm run coveralls
